
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>pyliburo.py3dmodel.OCCUtils.Construct module &#8212; Pyliburo 0.2a1 documentation</title>
    <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     '0.2a1',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true,
        SOURCELINK_SUFFIX: '.txt'
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
   
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head>
  <body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="module-pyliburo.py3dmodel.OCCUtils.Construct">
<span id="pyliburo-py3dmodel-occutils-construct-module"></span><h1>pyliburo.py3dmodel.OCCUtils.Construct module<a class="headerlink" href="#module-pyliburo.py3dmodel.OCCUtils.Construct" title="Permalink to this headline">¶</a></h1>
<p>This modules makes the construction of geometry a little easier</p>
<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.add_vector_to_point">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">add_vector_to_point</code><span class="sig-paren">(</span><em>self</em>, <em>vec</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.add_vector_to_point" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.add_wire_to_face">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">add_wire_to_face</code><span class="sig-paren">(</span><em>face</em>, <em>wire</em>, <em>reverse=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.add_wire_to_face" title="Permalink to this definition">¶</a></dt>
<dd><p>apply a wire to a face
use reverse to set the orientation of the wire to opposite
&#64;param face:
&#64;param wire:
&#64;param reverse:</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.boolean_cut">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">boolean_cut</code><span class="sig-paren">(</span><em>shapeToCutFrom</em>, <em>cuttingShape</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.boolean_cut" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.boolean_fuse">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">boolean_fuse</code><span class="sig-paren">(</span><em>shapeToCutFrom</em>, <em>joiningShape</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.boolean_fuse" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.compound">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">compound</code><span class="sig-paren">(</span><em>topo</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.compound" title="Permalink to this definition">¶</a></dt>
<dd><p>accumulate a bunch of TopoDS_* in list <cite>topo</cite> to a TopoDS_Compound
&#64;param topo: list of TopoDS_* instances</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.curve_to_bspline">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">curve_to_bspline</code><span class="sig-paren">(</span><em>crv_handle</em>, <em>tolerance=1e-05</em>, <em>continuity=2</em>, <em>sections=300</em>, <em>degree=12</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.curve_to_bspline" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.dir_to_vec">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">dir_to_vec</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.dir_to_vec" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.face_from_plane">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">face_from_plane</code><span class="sig-paren">(</span><em>_geom_plane</em>, <em>lowerLimit=-1000</em>, <em>upperLimit=1000</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.face_from_plane" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.face_normal">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">face_normal</code><span class="sig-paren">(</span><em>face</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.face_normal" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.find_plane_from_shape">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">find_plane_from_shape</code><span class="sig-paren">(</span><em>shape</em>, <em>tolerance=-1</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.find_plane_from_shape" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.fit_plane_through_face_vertices">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">fit_plane_through_face_vertices</code><span class="sig-paren">(</span><em>_face</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.fit_plane_through_face_vertices" title="Permalink to this definition">¶</a></dt>
<dd><table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><strong>_face</strong> – OCC.KBE.face.Face instance</td>
</tr>
<tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body">Geom_Plane</td>
</tr>
</tbody>
</table>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.fix_face">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">fix_face</code><span class="sig-paren">(</span><em>shp</em>, <em>tolerance=0.001</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.fix_face" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.fix_shape">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">fix_shape</code><span class="sig-paren">(</span><em>shp</em>, <em>tolerance=0.001</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.fix_shape" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.geodesic_path">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">geodesic_path</code><span class="sig-paren">(</span><em>pntA</em>, <em>pntB</em>, <em>edgA</em>, <em>edgB</em>, <em>kbe_face</em>, <em>n_segments=20</em>, <em>_tolerance=0.1</em>, <em>n_iter=20</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.geodesic_path" title="Permalink to this definition">¶</a></dt>
<dd><table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><ul class="first simple">
<li><strong>pntA</strong> – point to start from</li>
<li><strong>pntB</strong> – point to move towards</li>
<li><strong>edgA</strong> – edge to start from</li>
<li><strong>edgB</strong> – edge to move towards</li>
<li><strong>kbe_face</strong> – kbe.face.Face on which <cite>edgA</cite> and <cite>edgB</cite> lie</li>
<li><strong>n_segments</strong> – the number of segments the geodesic is built from</li>
<li><strong>_tolerance</strong> – tolerance when the geodesic is converged</li>
<li><strong>n_iter</strong> – maximum number of iterations</li>
</ul>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body"><p class="first last">TopoDS_Edge</p>
</td>
</tr>
</tbody>
</table>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_equal">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_Pnt_equal</code><span class="sig-paren">(</span><em>self</em>, <em>other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_equal" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_get_state">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_Pnt_get_state</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_get_state" title="Permalink to this definition">¶</a></dt>
<dd><p>pack as a tuple</p>
<p>used for copying / serializing the instance</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_set_state">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_Pnt_set_state</code><span class="sig-paren">(</span><em>self</em>, <em>state</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_Pnt_set_state" title="Permalink to this definition">¶</a></dt>
<dd><p>unpack tuple and return instance…</p>
<p>used for copying / serializing the instance</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_ax1_print">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_ax1_print</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_ax1_print" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_add">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_pnt_add</code><span class="sig-paren">(</span><em>self</em>, <em>other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_add" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_div">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_pnt_div</code><span class="sig-paren">(</span><em>self</em>, <em>other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_div" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_mul">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_pnt_mul</code><span class="sig-paren">(</span><em>self</em>, <em>other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_mul" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_print">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_pnt_print</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_print" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_sub">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_pnt_sub</code><span class="sig-paren">(</span><em>self</em>, <em>other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_pnt_sub" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_quat_print">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_quat_print</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_quat_print" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_trsf_print">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_trsf_print</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_trsf_print" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.gp_vec_print">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">gp_vec_print</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.gp_vec_print" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_circle">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_circle</code><span class="sig-paren">(</span><em>pnt</em>, <em>radius</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_circle" title="Permalink to this definition">¶</a></dt>
<dd><p>returns an edge
&#64;param pnt:
&#64;param radius:</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_constrained_surface_from_edges">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_constrained_surface_from_edges</code><span class="sig-paren">(</span><em>edges</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_constrained_surface_from_edges" title="Permalink to this definition">¶</a></dt>
<dd><p>DOESNT RESPECT BOUNDARIES</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_coons">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_coons</code><span class="sig-paren">(</span><em>edges</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_coons" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_evolved">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_evolved</code><span class="sig-paren">(</span><em>spine</em>, <em>profile</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_evolved" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_line">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_line</code><span class="sig-paren">(</span><em>pnt1</em>, <em>pnt2</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_line" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_loft">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_loft</code><span class="sig-paren">(</span><em>elements</em>, <em>ruled=False</em>, <em>tolerance=1e-05</em>, <em>continuity=4</em>, <em>check_compatibility=True</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_loft" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_n_sections">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_n_sections</code><span class="sig-paren">(</span><em>edges</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_n_sections" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_n_sided">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_n_sided</code><span class="sig-paren">(</span><em>edges</em>, <em>points</em>, <em>continuity=0</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_n_sided" title="Permalink to this definition">¶</a></dt>
<dd><p>builds an n-sided patch, respecting the constraints defined by <em>edges</em>
and <em>points</em></p>
<p>a simplified call to the BRepFill_Filling class
its simplified in the sense that to all constraining edges and points
the same level of <em>continuity</em> will be applied</p>
<p><em>continuity</em> represents:</p>
<p>GeomAbs_C0 : the surface has to pass by 3D representation of the edge
GeomAbs_G1 : the surface has to pass by 3D representation of the edge
and to respect tangency with the given face
GeomAbs_G2 : the surface has to pass by 3D representation of the edge
and to respect tangency and curvature with the given face.</p>
<p>NOTE: it is not required to set constraining points.
just leave the tuple or list empty</p>
<table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><ul class="first simple">
<li><strong>edges</strong> – the constraining edges</li>
<li><strong>points</strong> – the constraining points</li>
<li><strong>continuity</strong> – GeomAbs_0, 1, 2</li>
</ul>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body"><p class="first last">TopoDS_Face</p>
</td>
</tr>
</tbody>
</table>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_offset">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_offset</code><span class="sig-paren">(</span><em>wire_or_face</em>, <em>offsetDistance</em>, <em>altitude=0</em>, <em>joinType=0</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_offset" title="Permalink to this definition">¶</a></dt>
<dd><p>builds a offsetted wire or face from a wire or face
construct an offsetted version of the shape</p>
<p>&#64;param wire_or_face:        the wire or face to offset
&#64;param offsetDistance:      the distance to offset
&#64;param altitude:            move the offsetted shape to altitude
from the normal of the wire or face
&#64;param joinType:            the type of offset you want
can be one of GeomAbs_Arc, GeomAbs_Tangent, GeomAbs_Intersection</p>
<p>note: a shape that has a negative offsetDistance will return
a sharp corner</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_offset_shape">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_offset_shape</code><span class="sig-paren">(</span><em>shapeToOffset</em>, <em>offsetDistance</em>, <em>tolerance=1e-05</em>, <em>offsetMode=0</em>, <em>intersection=False</em>, <em>selfintersection=False</em>, <em>joinType=0</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_offset_shape" title="Permalink to this definition">¶</a></dt>
<dd><p>builds an offsetted shell from a shape
construct an offsetted version of the shape</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_oriented_box">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_oriented_box</code><span class="sig-paren">(</span><em>v_corner</em>, <em>v_x</em>, <em>v_y</em>, <em>v_z</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_oriented_box" title="Permalink to this definition">¶</a></dt>
<dd><p>produces an oriented box
oriented meaning here that the x,y,z axis do not have to be
cartesian aligned</p>
<table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><ul class="first simple">
<li><strong>v_corner</strong> – the lower corner</li>
<li><strong>v_x</strong> – gp_Vec that describes the X-axis</li>
<li><strong>v_y</strong> – gp_Vec that describes the Y-axis</li>
<li><strong>v_z</strong> – gp_Vec that describes the Z-axis</li>
</ul>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body"><p class="first last">TopoDS_Solid</p>
</td>
</tr>
</tbody>
</table>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_pipe">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_pipe</code><span class="sig-paren">(</span><em>spine</em>, <em>profile</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_pipe" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_plane">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_plane</code><span class="sig-paren">(</span><em>center=&lt; gp_Pnt: 0.0</em>, <em>0.0</em>, <em>0.0 &gt;</em>, <em>vec_normal=&lt; gp_Vec: 0.0</em>, <em>0.0</em>, <em>1.0</em>, <em>magnitude: 1.0 &gt;</em>, <em>extent_x_min=-100.0</em>, <em>extent_x_max=100.0</em>, <em>extent_y_min=-100.0</em>, <em>extent_y_max=100.0</em>, <em>depth=0.0</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_plane" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_prism">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_prism</code><span class="sig-paren">(</span><em>profile</em>, <em>vec</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_prism" title="Permalink to this definition">¶</a></dt>
<dd><p>makes a finite prism</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.make_ruled">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">make_ruled</code><span class="sig-paren">(</span><em>edgeA</em>, <em>edgeB</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.make_ruled" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.mirror_axe2">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">mirror_axe2</code><span class="sig-paren">(</span><em>brep</em>, <em>axe2</em>, <em>copy=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.mirror_axe2" title="Permalink to this definition">¶</a></dt>
<dd><p>&#64;param brep:
&#64;param line:</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.mirror_pnt_dir">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">mirror_pnt_dir</code><span class="sig-paren">(</span><em>brep</em>, <em>pnt</em>, <em>direction</em>, <em>copy=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.mirror_pnt_dir" title="Permalink to this definition">¶</a></dt>
<dd><p>&#64;param brep:
&#64;param line:</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.point_to_vector">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">point_to_vector</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.point_to_vector" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.project_edge_onto_plane">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">project_edge_onto_plane</code><span class="sig-paren">(</span><em>edg</em>, <em>plane</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.project_edge_onto_plane" title="Permalink to this definition">¶</a></dt>
<dd><table class="docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field-odd field"><th class="field-name">Parameters:</th><td class="field-body"><ul class="first simple">
<li><strong>edg</strong> – kbe.edge.Edge</li>
<li><strong>plane</strong> – Geom_Plane</li>
</ul>
</td>
</tr>
<tr class="field-even field"><th class="field-name">Returns:</th><td class="field-body"><p class="first last">TopoDS_Edge projected on the plane</p>
</td>
</tr>
</tbody>
</table>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.rotate">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">rotate</code><span class="sig-paren">(</span><em>brep</em>, <em>axe</em>, <em>degree</em>, <em>copy=True</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.rotate" title="Permalink to this definition">¶</a></dt>
<dd><p>&#64;param brep:
&#64;param axe:
&#64;param degree:</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.scale_uniformal">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">scale_uniformal</code><span class="sig-paren">(</span><em>brep</em>, <em>pnt</em>, <em>factor</em>, <em>copy=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.scale_uniformal" title="Permalink to this definition">¶</a></dt>
<dd><p>translate a brep over a vector
&#64;param brep:    the Topo_DS to translate
&#64;param pnt:     a gp_Pnt
&#64;param triple:  scaling factor
&#64;param copy:    copies to brep if True</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.sew_shapes">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">sew_shapes</code><span class="sig-paren">(</span><em>shapes</em>, <em>tolerance=0.001</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.sew_shapes" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.translate_topods_from_vector">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">translate_topods_from_vector</code><span class="sig-paren">(</span><em>brep_or_iterable</em>, <em>vec</em>, <em>copy=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.translate_topods_from_vector" title="Permalink to this definition">¶</a></dt>
<dd><p>translate a brep over a vector
&#64;param brep:    the Topo_DS to translate
&#64;param vec:     the vector defining the translation
&#64;param copy:    copies to brep if True</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.trim_wire">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">trim_wire</code><span class="sig-paren">(</span><em>wire</em>, <em>shapeLimit1</em>, <em>shapeLimit2</em>, <em>periodic=False</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.trim_wire" title="Permalink to this definition">¶</a></dt>
<dd><p>return the trimmed wire that lies between <cite>shapeLimit1</cite>
and <cite>shapeLimit2</cite>
returns TopoDS_Edge</p>
</dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.vec_to_dir">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">vec_to_dir</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.vec_to_dir" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="function">
<dt id="pyliburo.py3dmodel.OCCUtils.Construct.vector_to_point">
<code class="descclassname">pyliburo.py3dmodel.OCCUtils.Construct.</code><code class="descname">vector_to_point</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyliburo.py3dmodel.OCCUtils.Construct.vector_to_point" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

</div>


          </div>
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
<h1 class="logo"><a href="index.html">Pyliburo</a></h1>








<h3>Navigation</h3>

<div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="index.html">Documentation overview</a><ul>
  </ul></li>
</ul>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <form class="search" action="search.html" method="get">
      <div><input type="text" name="q" /></div>
      <div><input type="submit" value="Go" /></div>
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;2017, Chen Kian Wee.
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 1.6.3</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.10</a>
      
      |
      <a href="_sources/pyliburo.py3dmodel.OCCUtils.Construct.rst.txt"
          rel="nofollow">Page source</a>
    </div>

    

    
  </body>
</html>